### PR TITLE
feat : added filter component

### PR DESCRIPTION
**Pull request by SanjayJatti**
- Added 'filter.jsx' and 'filter.css' for filter component in product listing page
- Added customized data base according to my project
filter

### CODE REVIEW

**Review by ishapatell1 — APPROVED** [review]
Everything looks clean and readable. It would look even better if you adjust your search bar.

**Comment by SanjayJatti** [comment]
> Everything looks clean and readable. It would look even better if you adjust your search bar.

Sure...will look into it. Thanks!

**Review by prathmeshjagtap — APPROVED** [review]
code is Well Structured 
and I liked that you have created an array of different filters and then Mapped over that.

**Review by Kavita539 — APPROVED** [review]
- Nicely implemented the filter component, got clear picture about it.
- Liked the idea of mapping over an array through different filters.
- Code looks clean, structured and well maintained.
- UI also looks clean and minimal.

**Comment by SanjayJatti** [comment]
Thank you!

**Pull request merged**
